### ISSUE TITLE
Do we have a plan to support connection error detect?

### ISSUE THREAD

**Issue by froghui** [cloudfoundry-community/java-nats#30]
In particular case like network issue which leads to packet lost, nats-server will close the connection for the PING-PONG fails from server side to client side. While nats-clients still think the connection is good, it will result in error.
Do we have a plan to support either:
1. Use the tcp keepalive mechanism to let system tear down the connection and reconnect; (depends on the system config for tcp keepalive, which may not be a good solution)
2. Use Ping-pong method from client to nats-server.

**Comment by mheath** [comment]
Supporting client-side pings makes the most sense to me. I've never had good luck with TCP keep-alive.

@froghui Please test the change in the stale-connection-check branch and see if that works for you.

**Comment by froghui** [comment]
I've changed a little bit based on your commit and verified this fixed the issue.
https://github.com/cloudfoundry-community/java-nats/pull/31

**Comment by mheath** [comment]
Sorry @froghui, I've been busy the past little bit transitioning to a new job at Pivotal.

Help me understand why the user would want to configure the number of pongs that can be dropped. Wouldn't you want to close the connection and try to reconnect to the NATS cluster as soon as you detect one ping not getting a reply?

**Comment by froghui** [comment]
Hi, Mike,
This is very like tcp keepalive, that means we have interval and probes, which can be configured in different network environment.  http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#usingkeepalive is the reference.
By the way, the nats server uses the same way to detect the dead tcp connection.

**Comment by mheath** [comment]
Sorry, I should have commented on your pull-request, regardless.

TCP keepalive needs to send multiple probes in case the probe packet gets dropped by the network. If the NATS ping or pong frames get dropped, TCP will detect a dropped packet and resend the frame.

Your pull requests allows the client to miss more than one pong. I'm trying to understand the use case for doing that since TCP itself is already a reliable protocol.

I understand how the NATS server detects idle connections. I don't think it allows for multiple dropped pong frames from the client though.

**Comment by froghui** [comment]
Yes. I agree that TCP is a reliable protocol, but in complex network circumstance, the tcp package may be discarded or delayed, for example, network device power off or restart. We can not reply on the TCP itself to detect the stable connection, the application layer itself should detect the stable connection. 
Missing one pong from server side does not mean 100% accuracy that "this connection is dead". So we can leave it to user to decide the probe times. 
For the Nats server side, both the ruby and go version will close the connection after at least 2 pongs are not received. See https://github.com/nats-io/gnatsd/blob/master/server/client.go  Line 806

**Comment by mheath** [comment]
The change I made sends a NATS ping frame at regular intervals. Because TCP is a reliable protocol, if that ping frame does not get delivered, the NATS client will get a connection reset by peer exception, close the TCP connection, and try to reconnect to another server in the NATS cluster.

If the client doesn't receive any NATS frames (pong or otherwise) from the NATS server for two ping periods (perhaps this should be configured in its own property) it will close the connection assuming the NATS server is in a bad state.

So, back to my earlier message, I don't understand what problem the `pingMaxTimes` property in your pull request solves.
